# config/training_config.yaml

# Training parameters
batch_size: 8
num_epochs: 100
learning_rate: 1e-4
weight_decay: 1e-5
num_workers: 4

# Early stopping
patience: 10

# Scheduler parameters
T_0: 10  # Cosine annealing period
eta_min: 1e-6  # Minimum learning rate

# Training options
grad_clip: 1.0
mixed_precision: true

# Model parameters
in_channels: 1
out_channels: 4