_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
                - 80
            "2":
                - 1
                - 55
                - 80
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
T_0:
    value: 10
accumulation_steps:
    value: 1
batch_size:
    value: 8
device:
    value: cpu
eta_min:
    value: 1e-06
grad_clip:
    value: 1
in_channels:
    value: 1
learning_rate:
    value: 0.0001
mixed_precision:
    value: true
num_epochs:
    value: 100
num_workers:
    value: 4
out_channels:
    value: 4
patience:
    value: 10
pin_memory:
    value: true
seed:
    value: 42
val_split:
    value: 0.2
weight_decay:
    value: 1e-05
